# Copyright (C) 2024 - 2025 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: Dynamic Uses

on:
  pull_request:
    # opened, reopened, and synchronize are default for pull_request
    # edited - when PR title or body is changed
    # labeled - when labels are added to PR
    # closed: removed since it might cancel the run related to merge on main
    # --> skip doc-deploy-pr
    # types: [opened, reopened, synchronize, edited, labeled, closed]
    types: [opened, reopened, synchronize, edited, labeled]
  push:
    tags:
      - "*"
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:

  test-dynamic-uses:
    uses: ./.github/workflows/scade-ext-workflow.yml
    permissions:
      attestations: write
      contents: write
      id-token: write
      pull-requests: write
    with:
      documentation-cname: 'not-applicable'
      library-name: 'not-applicable'
      repository-name: 'not-applicable'
      is-public: false
      # unit test specific inputs
      library-dir: "tests/python-pyproject"
      pytest-postargs: "tests/python-pyproject/tests -vv"
      # skip all steps but scade-tests
      skip-labeler: true
      skip-changelog-fragment: true
      skip-pr-name: true
      skip-code-style: true
      skip-doc-style: true
      skip-check-vulnerabilities: true
      skip-update-changelog: true
      skip-build-wheelhouse: true
      # skip-scade-tests: true
      skip-python-tests: true
      skip-doc-build: true
      skip-doc-deploy-pr: true
      skip-build-library: true
      skip-release: true
      skip-doc-deploy-dev: true
      skip-doc-deploy-stable: true
      # strategies
      build-wheelhouse-versions: "['3.10']"
      python-tests-versions: "['3.10', '3.12']"
    secrets:
      PYANSYS_CI_BOT_TOKEN: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
      PYANSYS_CI_BOT_USERNAME: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
      PYANSYS_CI_BOT_EMAIL: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}
      PYANSYS_PYPI_PRIVATE_PAT : ${{ secrets.PYANSYS_PYPI_PRIVATE_PAT }}
